# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inference_to_Tag_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferencetoTagMap_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferencetag', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagModifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagModifier', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inference_to_tag_map',
            name='inferenceTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.InferenceTags'),
        ),
        migrations.AddField(
            model_name='inference_to_tag_map',
            name='mod_tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.TagModifiers'),
        ),
        migrations.AddField(
            model_name='inference_to_tag_map',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.TrainingTags'),
        ),
    ]
