# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inference_to_tag_map',
            name='inferencetoTagMap_id',
        ),
    ]
