# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_auto_20180518_0926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inference_to_tag_map',
            table='Inference_to_Tag_Map',
        ),
        migrations.AlterModelTable(
            name='inferencetags',
            table='InferenceTags',
        ),
        migrations.AlterModelTable(
            name='tagmodifiers',
            table='tagModifiers',
        ),
        migrations.AlterModelTable(
            name='trainingtags',
            table='TrainingTags',
        ),
    ]
